# Generated by Django 4.1 on 2022-09-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tecnicord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('carga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pulverizadoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('litros', models.IntegerField()),
            ],
        ),
    ]
