# Generated by Django 4.1 on 2022-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tecnicord', '0002_camiones_pulverizadoras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiones',
            name='carga',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='pulverizadoras',
            name='litros',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tractores',
            name='potencia',
            field=models.IntegerField(unique=True),
        ),
    ]
